# Colors (Gruvbox dark)

# Default colors
[colors.primary]
background = '#202525'
foreground = '#fbebc2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#dc241d'
green   = '#98971a'
yellow  = '#d7b921'
blue    = '#4585f8'
magenta = '#b16286'
cyan    = '#aaaaaa'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Source Code Pro"}
size = 10
